import { ProvisionAmendmentDetail } from './types';

/** Entri dampak: Pasal 28, 26, 36, 40, 40A, 45. */
export const MAP_LAINNYA: Record<string, ProvisionAmendmentDetail> = {
  // ── Pasal 28 & Ayat-Ayatnya ───────────────────────────────────────────────
  'uu-11-2008/pasal-28': {
    canonicalPath: 'uu-11-2008/pasal-28',
    pasalLabel: 'Pasal 28',
    diubahOleh: 'UU No. 1 Tahun 2024 tentang Perubahan Kedua UU ITE (Pasal I angka 4)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'Lembaran Negara Republik Indonesia Tahun 2024 Nomor 8, Tambahan Lembaran Negara Nomor 6916',
    statusPerubahan: 'DIUBAH',
    statusBadge: '🟡 Diubah & Ditambah Ayat (UU 1/2024)',
    textSebelum: 'Pasal 28 memuat 2 ayat: (1) Berita bohong yang merugikan konsumen dalam transaksi elektronik; (2) Informasi untuk menimbulkan rasa kebencian SARA.',
    textSesudah: 'Pasal 28 ayat (1) dan (2) disempurnakan redaksinya, serta DITAMBAHKAN ayat (3) baru mengenai larangan penyebaran berita bohong yang menimbulkan kerusuhan di kalangan masyarakat.',
    putusanMk: {
      nomor: 'Putusan MK No. 78/PUU-XXI/2023',
      tahun: 2023,
      amarPutusan: 'Membatalkan Pasal 14 dan 15 UU No. 1 Tahun 1946 (delik menyiarkan berita bohong yang menerbitkan keonaran di kalangan rakyat).',
      ratioDecidendi: 'Ukuran keonaran dalam rumusan kuno tidak memiliki parameter objektif dan bertentangan dengan UUD 1945.',
    },
    latarBelakangPerubahan: 'Menambahkan Pasal 28 ayat (3) baru mengenai larangan penyebaran berita bohong yang menimbulkan kerusuhan di masyarakat, dengan ancaman pidana maksimal 6 tahun, menggantikan kekosongan hukum pasca pembatalan pasal keonaran di KUHP lama.',
    peraturanTerdampak: [
      {
        id: 'permenkominfo-5-2020-pasal-14',
        type: 'PERMEN',
        number: 'Permenkominfo No. 5 Tahun 2020',
        year: 2020,
        title: 'PSE Lingkup Privat',
        pasalTurunan: 'Pasal 14 (Takedown Mendesak 4 Jam)',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Perlu Penyesuaian Harmonisasi',
        ringkasanDampak: 'Kewenangan permintaan pemutusan akses darurat 4 jam untuk berita bohong harus dibuktikan memenuhi unsur kerusuhan nyata sesuai Pasal 28 ayat (3).',
        uuIndukSebelum: 'Pasal 28 hanya mengatur kerugian konsumen (ayat 1) dan ujaran kebencian SARA (ayat 2).',
        uuIndukSesudah: 'Ditambahkan ayat (3) tentang berita bohong penyebab kerusuhan fisik nyata di kalangan rakyat.',
        ketentuanTurunanTerdampak: 'Pasal 14 Permenkominfo No. 5 Tahun 2020 mengenai permohonan takedown mendesak.',
        penjelasanPertentangan: 'Permenkominfo saat ini mengizinkan pemblokiran informasi atas dasar permohonan instansi tanpa verifikasi ada tidaknya potensi kerusuhan riil di lapangan.',
        rekomendasiHarmonisasi: 'Revisi Permenkominfo dengan menetapkan SOP verifikasi faktual bersama aparat keamanan sebelum perintah takedown 4 jam diterbitkan.',
      },
    ],
  },

  // ── Pasal 28 ayat (3) ─────────────────────────────────────────────────────
  'uu-11-2008/pasal-28/ayat-3': {
    canonicalPath: 'uu-11-2008/pasal-28/ayat-3',
    pasalLabel: 'Pasal 28 ayat (3)',
    diubahOleh: 'UU No. 1 Tahun 2024 (Pasal I angka 4 huruf c)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'SISIPAN_BARU',
    statusBadge: '🟢 Ayat Sisipan Baru (UU 1/2024)',
    textSebelum: '(Ketentuan ayat belum ada pada naskah UU ITE 2008 maupun UU ITE 2016)',
    textSesudah: 'Setiap Orang dengan sengaja menyebarkan Informasi Elektronik dan/atau Dokumen Elektronik yang diketahuinya memuat pemberitahuan bohong yang menimbulkan kerusuhan di masyarakat.',
    putusanMk: {
      nomor: 'Putusan MK No. 78/PUU-XXI/2023',
      tahun: 2023,
      amarPutusan: 'Membatalkan delik keonaran KUHP lama (UU 1/1946).',
      ratioDecidendi: 'Istilah kerusuhan harus dimaknai sebagai kekacauan fisik nyata di ruang publik, bukan sekadar perdebatan sengit atau viral di media sosial.',
    },
    latarBelakangPerubahan: 'Pengganti pasal keonaran kuno dengan kualifikasi "kerusuhan di masyarakat" yang harus dibuktikan secara materiil adanya huru-hara atau kekerasan fisik.',
    peraturanTerdampak: [
      {
        id: 'skb-berita-bohong-2024',
        type: 'SKB',
        number: 'Surat Edaran Bersama Jaksa Agung & Kapolri',
        year: 2024,
        title: 'Pedoman Penuntutan Delik Hoaks Penyebab Kerusuhan',
        pasalTurunan: 'Bab Pembuktian Materiil Kerusuhan',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ SOP Pembuktian Kerusuhan Nyata',
        ringkasanDampak: 'Penyidik wajib menghadirkan bukti dampak fisik kerusuhan di lapangan, bukan sekadar kegaduhan netizen di linimasa.',
        uuIndukSebelum: 'Belum ada ketentuan Pasal 28 ayat (3).',
        uuIndukSesudah: 'Pasal 28 ayat (3) UU 1/2024 mewajibkan kausalitas nyata antara hoaks dengan kerusuhan.',
        ketentuanTurunanTerdampak: 'SOP penyelidikan tindak pidana hoaks di kepolisian.',
        penjelasanPertentangan: 'Penyidikan hoaks tanpa adanya insiden fisik kerusuhan gugur demi hukum.',
        rekomendasiHarmonisasi: 'Penerbitan pedoman penegakan hukum siber presisi oleh Bareskrim Polri.',
      },
    ],
  },

  // ── Pasal 26 (Data Pribadi & Right to be Forgotten) ───────────────────────
  'uu-11-2008/pasal-26': {
    canonicalPath: 'uu-11-2008/pasal-26',
    pasalLabel: 'Pasal 26',
    diubahOleh: 'UU No. 19 Tahun 2016 tentang Perubahan UU ITE (Pasal I angka 2)',
    tanggalPengundangan: 'Disahkan: 25 November 2016 | Diundangkan: 28 November 2016',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Menkumham Yasonna H. Laoly',
    lembaranNegara: 'LN RI Tahun 2016 No. 251, TLN No. 5952',
    statusPerubahan: 'DIUBAH',
    statusBadge: '🟡 Diubah Amandemen I & Harmonisasi UU PDP',
    textSebelum: 'Pasal 26 hanya memuat 2 ayat: (1) Penggunaan data pribadi harus dengan persetujuan; (2) Gugatan atas kerugian pelanggaran data pribadi.',
    textSesudah: 'Ditambahkan ayat (3), (4), dan (5) yang mewajibkan PSE menghapus Informasi Elektronik yang tidak relevan (Right to be Forgotten) atas penetapan pengadilan.',
    latarBelakangPerubahan: 'Amandemen I menyisipkan ayat (3), (4), dan (5) yang mewajibkan PSE menghapus informasi elektronik yang tidak relevan (Right to be Forgotten) berdasarkan penetapan pengadilan negeri.',
    peraturanTerdampak: [
      {
        id: 'uu-pdp-2022',
        type: 'UU',
        number: 'UU No. 27 Tahun 2022',
        year: 2022,
        title: 'Undang-Undang tentang Pelindungan Data Pribadi (UU PDP)',
        pasalTurunan: 'Pasal 43 & Pasal 44 UU PDP',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Harmonisasi Lex Specialis',
        ringkasanDampak: 'Ketentuan pemrosesan dan penghapusan data pribadi pada Pasal 26 UU ITE tunduk pada standar kepatuhan pengendali data dalam UU PDP.',
        uuIndukSebelum: 'Pasal 26 UU ITE 2008 hanya mengatur persetujuan pemilik data secara umum.',
        uuIndukSesudah: 'UU PDP 2022 berlaku penuh sebagai hukum khusus pelindungan data pribadi (Lex Specialis).',
        ketentuanTurunanTerdampak: 'Pasal 14 sampai Pasal 16 PP No. 71 Tahun 2019 tentang tata cara penghapusan informasi data pribadi.',
        penjelasanPertentangan: 'Mekanisme penghapusan di PP 71/2019 masih berfokus pada penetapan pengadilan, sedangkan UU PDP memberikan hak penghapusan langsung kepada subjek data.',
        rekomendasiHarmonisasi: 'Sinkronisasi RPP Turunan UU PDP dengan aturan teknis PSE di PP 71/2019.',
      },
    ],
  },

  // ── Pasal 36 (Pemberatan Kerugian - Dicabut UU 1/2024) ────────────────────
  'uu-11-2008/pasal-36': {
    canonicalPath: 'uu-11-2008/pasal-36',
    pasalLabel: 'Pasal 36',
    diubahOleh: 'UU No. 1 Tahun 2024 (Pasal I angka 8 - Dihapus)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'DICABUT',
    statusBadge: '🔴 Ketentuan Norma Dihapus / Dicabut (UU 1/2024)',
    textSebelum: 'Setiap Orang dengan sengaja dan tanpa hak atau melawan hukum melakukan perbuatan sebagaimana dimaksud dalam Pasal 27 sampai dengan Pasal 34 yang mengakibatkan kerugian bagi Orang lain.',
    textSesudah: '[PASAL 36 DIHAPUS OLEH PASAL I ANGKA 8 UU NO. 1 TAHUN 2024]. Ketentuan pemberatan pidana penjara 12 tahun akibat kerugian materiil tidak berlaku lagi.',
    latarBelakangPerubahan: 'Pasal 36 dihapus karena sering dijadikan alat oleh aparat penegak hukum untuk mem-bypass ancaman pidana di bawah 5 tahun (agar tersangka bisa ditahan dengan dalih ada kerugian pihak lain hingga Rp 12 miliar).',
    peraturanTerdampak: [
      {
        id: 'skb-pasal-36-2021',
        type: 'SKB',
        number: 'Pedoman Penuntutan Jaksa Agung RI',
        year: 2021,
        title: 'Pedoman Penerapan Pasal Pemberatan Kerugian UU ITE',
        pasalTurunan: 'Matriks Penuntutan Kumulatif Pasal 36',
        status: 'USANG',
        statusLabel: '🔴 Tidak Berlaku Lagi (Objek Dihapus)',
        ringkasanDampak: 'Jaksa penuntut umum dilarang menambahkan dakwaan subsidair Pasal 36 jo. Pasal 51 ayat (2).',
        uuIndukSebelum: 'Pasal 36 memuat delik kerugian materiil dengan ancaman Pasal 51 ayat (2) hingga 12 tahun penjara.',
        uuIndukSesudah: 'Pasal 36 DICABUT 100% dari sistem hukum pidana siber Indonesia.',
        ketentuanTurunanTerdampak: 'Surat Tuntutan dan Dakwaan Kejaksaan.',
        penjelasanPertentangan: 'Pencantuman Pasal 36 pasca 2 Januari 2024 mengakibatkan surat dakwaan cacat yuridis.',
        rekomendasiHarmonisasi: 'Kejaksaan Agung menerbitkan edaran penarikan seluruh berkas yang mencantumkan Pasal 36.',
      },
    ],
  },

  // ── Pasal 40 & 40A (Pemutusan Akses & Pelindungan Anak) ───────────────────
  'uu-11-2008/pasal-40': {
    canonicalPath: 'uu-11-2008/pasal-40',
    pasalLabel: 'Pasal 40',
    diubahOleh: 'UU No. 1 Tahun 2024 & UU No. 19 Tahun 2016 (Pasal I angka 9)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'DIUBAH',
    statusBadge: '🟡 Diubah & Disisipkan Pasal 40A (UU 1/2024)',
    textSebelum: 'Pemerintah memfasilitasi pemanfaatan Teknologi Informasi dan melindungi kepentingan umum dari segala jenis gangguan (UU 19/2016 menambahkan pemutusan akses).',
    textSesudah: 'Pemerintah bertanggung jawab mencegah penyebarluasan muatan yang dilarang dan berwenang memutus akses atau memerintahkan PSE memutus akses terhadap informasi/dokumen elektronik yang melanggar hukum.',
    latarBelakangPerubahan: 'Pemerintah diberi kewenangan memutus akses informasi elektronik yang melanggar hukum, sekaligus disisipkan Pasal 40A yang mewajibkan PSE memberikan perlindungan bagi anak dalam penggunaan sistem elektronik.',
    peraturanTerdampak: [
      {
        id: 'rpp-anak-siber-2024',
        type: 'PP',
        number: 'Mandat RPP Pelindungan Anak di Ruang Siber',
        year: 2024,
        title: 'Rancangan Peraturan Pemerintah Pelindungan Anak dalam PSE',
        pasalTurunan: 'Mandat Pasal 40A ayat (4) UU 1/2024',
        status: 'MANDAT_BARU',
        statusLabel: '🟢 Mandat Pembentukan PP Baru (Maks. 2 Tahun)',
        ringkasanDampak: 'Pemerintah diwajibkan mengundangkan PP khusus perlindungan anak paling lambat 2 Januari 2026.',
        uuIndukSebelum: 'Tidak ada ketentuan kewajiban khusus proteksi anak pada UU ITE 2008 maupun 2016.',
        uuIndukSesudah: 'Pasal 40A UU 1/2024: PSE wajib membatasi konten, menyediakan mekanisme verifikasi usia, dan kanal pengaduan ramah anak.',
        ketentuanTurunanTerdampak: 'Belum ada aturan pelaksana (sedang dalam proses harmonisasi antarkementerian).',
        penjelasanPertentangan: 'Tanpa PP pelaksana, PSE multinasional belum memiliki pedoman teknis standar verifikasi umur di Indonesia.',
        rekomendasiHarmonisasi: 'Kementerian Komdigi bersama KemenPPPA mempercepat penetapan RPP Pelindungan Anak di Ruang Siber.',
      },
      {
        id: 'pp-71-2019-pasal-96',
        type: 'PP',
        number: 'PP No. 71 Tahun 2019',
        year: 2019,
        title: 'PSTE',
        pasalTurunan: 'Pasal 96 & 97 (Sanksi Administratif)',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Perlu Penambahan Sanksi Pasal 40A',
        ringkasanDampak: 'Tabel sanksi denda administratif PP 71/2019 perlu diperluas mencakup pelanggaran perlindungan anak.',
        uuIndukSebelum: 'Sanksi administratif hanya terkait pendaftaran dan tata kelola PSE umum.',
        uuIndukSesudah: 'Pasal 40A ayat (3) UU 1/2024 menetapkan sanksi administratif teguran hingga denda bagi PSE yang abai melindungi anak.',
        ketentuanTurunanTerdampak: 'Mekanisme denda administratif pada PP 71/2019.',
        penjelasanPertentangan: 'PP belum mengatur besaran denda administratif untuk pelanggaran keamanan anak di platform digital.',
        rekomendasiHarmonisasi: 'Menyusun Peraturan Pemerintah perubahan atas PP 71/2019 terkait skema denda administratif.',
      },
    ],
  },

  // ── Pasal 40A (Sisipan Baru UU 1/2024 - Perlindungan Anak) ────────────────
  'uu-11-2008/pasal-40a': {
    canonicalPath: 'uu-11-2008/pasal-40a',
    pasalLabel: 'Pasal 40A',
    diubahOleh: 'UU No. 1 Tahun 2024 (Pasal I angka 10)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'SISIPAN_BARU',
    statusBadge: '🟢 Sisipan Baru (Kewajiban PSE Melindungi Anak)',
    textSebelum: '(Ketentuan norma belum ada pada UU No. 11 Tahun 2008 maupun UU No. 19 Tahun 2016)',
    textSesudah: '(1) Penyelenggara Sistem Elektronik wajib memberikan pelindungan bagi anak dalam penggunaan Sistem Elektronik.\n(2) Pelindungan meliputi verifikasi usia, moderasi konten kekerasan seksual/eksploitasi, dan saluran pengaduan khusus.\n(3) Pelanggaran dikenai sanksi administratif teguran tertulis, denda administratif, hingga pemutusan akses.',
    latarBelakangPerubahan: 'Merupakan amanat baru hukum positif Indonesia pasca ratifikasi konvensi hak anak dan maraknya predator seksual anak online serta kecanduan game/judi pada anak di bawah umur.',
    peraturanTerdampak: [
      {
        id: 'pp-ramah-anak-2024',
        type: 'PP',
        number: 'RPP Mandat Pasal 40A',
        year: 2024,
        title: 'Tata Cara Pelindungan Anak dalam Penyelenggaraan Sistem Elektronik',
        pasalTurunan: 'Seluruh RPP Baru',
        status: 'MANDAT_BARU',
        statusLabel: '🟢 Mandat Pembentukan PP Baru',
        ringkasanDampak: 'Kementerian Komunikasi dan Digital wajib merampungkan draf PP sebelum Januari 2026.',
        uuIndukSebelum: 'Belum diatur dalam UU ITE.',
        uuIndukSesudah: 'Pasal 40A ayat (4) UU 1/2024: Ketentuan lebih lanjut mengenai pelindungan anak diatur dalam Peraturan Pemerintah.',
        ketentuanTurunanTerdampak: 'Regulasi operasional PSE anak.',
        penjelasanPertentangan: 'Bila PP tidak kunjung terbit, penegakan sanksi denda administratif Pasal 40A ayat (3) tidak dapat dieksekusi.',
        rekomendasiHarmonisasi: 'Akselerasi harmonisasi antarkementerian di Kemenkumham RI.',
      },
    ],
  },

  // ── Pasal 45 (Ketentuan Sanksi Pidana) ────────────────────────────────────
  'uu-11-2008/pasal-45': {
    canonicalPath: 'uu-11-2008/pasal-45',
    pasalLabel: 'Pasal 45',
    diubahOleh: 'UU No. 1 Tahun 2024 (Pasal I angka 14) jo. UU No. 19 Tahun 2016',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'DIUBAH',
    statusBadge: '🟡 Restrukturisasi Sanksi Pidana (UU 1/2024)',
    textSebelum: 'Pasal 45 memuat ancaman pidana penjara paling lama 6 tahun (UU 11/2008) dan 4 tahun (UU 19/2016) untuk tindak pidana pencemaran nama baik.',
    textSesudah: 'Pasal 45 ayat (4) UU 1/2024 menetapkan ancaman pidana penghinaan/pencemaran Pasal 27A dipangkas menjadi penjara paling lama 2 tahun atau denda paling banyak Rp400 juta. Tersangka TIDAK DAPAT DITAHAN selama penyidikan.',
    putusanMk: {
      nomor: 'Putusan MK No. 50/PUU-VI/2008 & No. 2/PUU-VII/2009',
      tahun: 2008,
      amarPutusan: 'Menguatkan sifat delik aduan dan keselarasan sanksi dengan KUHP.',
      ratioDecidendi: 'Menjamin proporsionalitas penjatuhan pidana agar tidak melampaui ancaman delik pokok dalam hukum pidana materiil.',
    },
    latarBelakangPerubahan: 'Ancaman pidana penjara untuk penghinaan dan pencemaran diturunkan secara bertahap: dari 6 tahun (UU 11/2008) menjadi 4 tahun (UU 19/2016), dan dalam UU 1/2024 ancaman Pasal 27A dipatok maksimal 2 tahun penjara atau denda Rp400 juta. Dengan ancaman 2 tahun, tersangka TIDAK BISA DITAHAN selama proses penyidikan (Pasal 21 KUHAP).',
    peraturanTerdampak: [
      {
        id: 'perkap-penyidikan-2024',
        type: 'PERMEN',
        number: 'Perkap / Perpol Penanganan Tindak Pidana Siber',
        year: 2024,
        title: 'Standar Operasional Prosedur Penyidikan Siber Bareskrim Polri',
        pasalTurunan: 'SOP Penahanan & Keadilan Restoratif (Restorative Justice)',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Larangan Penahanan Tersangka',
        ringkasanDampak: 'Penyidik kepolisian dilarang melakukan penahanan terhadap tersangka dugaan tindak pidana Pasal 27A UU ITE.',
        uuIndukSebelum: 'Pasal 45 ayat (1) UU 11/2008 ancaman 6 tahun (dapat ditahan langsung oleh penyidik).',
        uuIndukSesudah: 'Pasal 45 ayat (4) UU 1/2024 ancaman maksimal hanya 2 tahun.',
        ketentuanTurunanTerdampak: 'SOP Penyidikan Siber Polri mengenai syarat objektif penahanan (Pasal 21 KUHAP mensyaratkan pidana di atas 5 tahun).',
        penjelasanPertentangan: 'Penahanan tersangka pada kasus pencemaran nama baik di medsos pasca UU 1/2024 adalah tindakan unprocedural (cacat hukum) dan dapat dipraperadilankan.',
        rekomendasiHarmonisasi: 'Kapolri mengeluarkan Surat Telegram Rahasia (STR) penegasan larangan penahanan tersangka Pasal 27A dan wajib mengutamakan Restorative Justice.',
      },
    ],
  }
};
