import { ProvisionAmendmentDetail } from './types';

/** Entri dampak: keluarga Pasal 27 & sisipan 27A/27B (UU 1/2024). */
export const MAP_PASAL_27: Record<string, ProvisionAmendmentDetail> = {
  // ── Pasal 27 & Ayat-Ayatnya ───────────────────────────────────────────────
  'uu-11-2008/pasal-27': {
    canonicalPath: 'uu-11-2008/pasal-27',
    pasalLabel: 'Pasal 27',
    diubahOleh: 'UU No. 1 Tahun 2024 tentang Perubahan Kedua UU ITE (Pasal I angka 2)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'Lembaran Negara Republik Indonesia Tahun 2024 Nomor 8, Tambahan Lembaran Negara Nomor 6916',
    statusPerubahan: 'DIUBAH',
    statusBadge: '🟡 Diubah & Dipecah (UU 1/2024)',
    textSebelum: 'Pasal 27 memuat 4 ayat: (1) Kesusilaan; (2) Perjudian; (3) Penghinaan atau pencemaran nama baik; (4) Pemerasan dan/atau pengancaman.',
    textSesudah: 'Pasal 27 ayat (1) diubah redaksinya (dikecualikan untuk kepentingan umum/pembelaan diri/seni); ayat (2) diubah mempertegas judi online; ayat (3) dan ayat (4) DIHAPUS dan dipisahkan menjadi Pasal 27A dan Pasal 27B.',
    putusanMk: {
      nomor: 'Putusan MK No. 50/PUU-VI/2008 & No. 2/PUU-VII/2009',
      tahun: 2008,
      amarPutusan: 'Menolak permohonan untuk seluruhnya — Pasal 27 ayat (3) tetap berlaku; sifat delik aduan absolut (klachtdelict) dengan rujukan Pasal 310 dan 311 KUHP ditegaskan dalam pertimbangan MK.',
      ratioDecidendi: 'Penghormatan terhadap martabat seseorang adalah hak individual, sehingga penegakan hukum hanya boleh dilakukan atas kehendak bebas korban secara langsung.',
    },
    latarBelakangPerubahan: 'Pasal 27 direstrukturisasi secara mendasar dalam UU 1/2024: ayat (3) dihapus dan dipisahkan menjadi Pasal 27A (penyerangan kehormatan) dan Pasal 27B (pemerasan dan pengancaman) untuk mengakhiri multi-interpretasi "pasal karet" dan melindungi kemerdekaan berekspresi.',
    peraturanTerdampak: [
      {
        id: 'pp-71-2019-pasal-5',
        type: 'PP',
        number: 'PP No. 71 Tahun 2019',
        year: 2019,
        title: 'Penyelenggaraan Sistem dan Transaksi Elektronik (PSTE)',
        pasalTurunan: 'Pasal 5 ayat (2) & Pasal 21',
        status: 'HILANG_CANTOLAN',
        statusLabel: '⚠️ Kehilangan Cantolan Yuridis',
        ringkasanDampak: 'Kewajiban moderasi dan takedown konten pencemaran nama baik oleh PSE di PP 71/2019 masih bersandar pada Pasal 27 ayat (3) lama yang kini telah dicabut.',
        uuIndukSebelum: 'Pasal 27 ayat (3) UU 11/2008: "Setiap Orang dengan sengaja dan tanpa hak mendistribusikan... muatan penghinaan dan/atau pencemaran nama baik."',
        uuIndukSesudah: 'Pasal 27 ayat (3) DIHAPUS oleh UU 1/2024. Norma dialihkan ke Pasal 27A sebagai delik aduan khusus dengan syarat formil pengaduan korban langsung.',
        ketentuanTurunanTerdampak: 'Pasal 5 ayat (2) PP 71/2019: "PSE wajib memastikan Sistem Elektroniknya tidak memuat Informasi Elektronik yang dilarang sesuai ketentuan peraturan perundang-undangan."',
        penjelasanPertentangan: 'Karena Pasal 27 ayat (3) telah dihapus dari undang-undang pokok, PSE dan Kemenkominfo tidak dapat lagi melakukan takedown sepihak atas tuduhan pencemaran nama baik tanpa adanya aduan resmi dari pihak yang diserang kehormatannya.',
        rekomendasiHarmonisasi: 'Pemerintah perlu merevisi PP 71/2019 dengan menghapus kategori pencemaran nama baik dari daftar konten negatif yang dapat ditindak secara administratif tanpa penetapan pengadilan.',
      },
      {
        id: 'permenkominfo-5-2020-pasal-9',
        type: 'PERMEN',
        number: 'Permenkominfo No. 5 Tahun 2020',
        year: 2020,
        title: 'Penyelenggara Sistem Elektronik Lingkup Privat',
        pasalTurunan: 'Pasal 9 ayat (4) & Pasal 13',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Perlu Penyesuaian Harmonisasi',
        ringkasanDampak: 'Kewenangan pemutusan akses 1x24 jam terhadap konten yang "meresahkan masyarakat" bertentangan dengan asas kepastian hukum UU 1/2024.',
        uuIndukSebelum: 'Ketentuan pemutusan akses UU 19/2016 Pasal 40 ayat (2b) tanpa batasan delik aduan.',
        uuIndukSesudah: 'Pasal 27A & Pasal 28 ayat (3) UU 1/2024 mensyaratkan pembuktian kerusuhan fisik nyata di ruang publik dan delik aduan perseorangan.',
        ketentuanTurunanTerdampak: 'Pasal 9 ayat (4) huruf a Permenkominfo 5/2020: "Konten dilarang mencakup informasi yang meresahkan masyarakat dan mengganggu ketertiban umum."',
        penjelasanPertentangan: 'Frasa "meresahkan masyarakat" pada Permenkominfo tidak memiliki cantolan hukum dalam UU ITE terbaru, sehingga berpotensi menjadi dasar pemblokiran sepihak yang melanggar hak asasi.',
        rekomendasiHarmonisasi: 'Kementerian Komdigi wajib menyesuaikan Permenkominfo 5/2020 dengan mendefinisikan batas pemutusan akses secara ketat merujuk norma Pasal 27A dan 28 ayat (3) UU 1/2024.',
      },
      {
        id: 'skb-3-menteri-2021',
        type: 'SKB',
        number: 'SKB Menkominfo, Jaksa Agung, & Kapolri No. 229/2021',
        year: 2021,
        title: 'Pedoman Implementasi Kriteria Penerapan UU ITE',
        pasalTurunan: 'Pedoman Angka 3 (Pasal 27 ayat 3)',
        status: 'USANG',
        statusLabel: '🔴 Tidak Berlaku Lagi (Usang)',
        ringkasanDampak: 'Pedoman implementasi Pasal 27 ayat (3) kehilangan objek hukum karena pasalnya telah dihapus dari undang-undang pokok.',
        uuIndukSebelum: 'Pasal 27 ayat (3) UU ITE 2016.',
        uuIndukSesudah: 'Pasal 27 ayat (3) DICABUT dan digantikan oleh Pasal 27A & 27B UU 1/2024.',
        ketentuanTurunanTerdampak: 'Seluruh matriks interpretasi Pasal 27 ayat (3) dalam Lampiran SKB 3 Menteri Tahun 2021.',
        penjelasanPertentangan: 'Instrumen SKB tidak dapat lagi dijadikan rujukan hukum acara pidana bagi kepolisian dan kejaksaan karena pasalnya sudah tidak eksis dalam hukum positif.',
        rekomendasiHarmonisasi: 'Kapolri dan Jaksa Agung wajib menerbitkan Surat Edaran atau Peraturan Bersama baru yang mendasarkan penuntutan pada Pasal 27A dan 27B UU 1/2024.',
      },
    ],
  },

  // ── Pasal 27 ayat (1) ─────────────────────────────────────────────────────
  'uu-11-2008/pasal-27/ayat-1': {
    canonicalPath: 'uu-11-2008/pasal-27/ayat-1',
    pasalLabel: 'Pasal 27 ayat (1)',
    diubahOleh: 'UU No. 1 Tahun 2024 (Pasal I angka 2 huruf a)',
    tanggalPengundangan: 'Disahkan: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'DIUBAH',
    statusBadge: '🟡 Redaksi Diperjelas (UU 1/2024)',
    textSebelum: 'Setiap Orang dengan sengaja dan tanpa hak mendistribusikan dan/atau mentransmisikan dan/atau membuat dapat diaksesnya Informasi Elektronik dan/atau Dokumen Elektronik yang memiliki muatan yang melanggar kesusilaan.',
    textSesudah: 'Setiap Orang dengan sengaja dan tanpa hak menyiarkan, mempertunjukkan, mendistribusikan, mentransmisikan, dan/atau membuat dapat diaksesnya Informasi Elektronik dan/atau Dokumen Elektronik yang memiliki muatan yang melanggar kesusilaan untuk diketahui umum.',
    latarBelakangPerubahan: 'Menambahkan frasa "untuk diketahui umum" serta klausul pengecualian dalam penjelasan untuk karya seni, budaya, ilmu pengetahuan, atau pembelaan diri agar ranah privasi warga tidak dikriminalisasi.',
    peraturanTerdampak: [
      {
        id: 'pp-71-2019-pasal-5-p27a1',
        type: 'PP',
        number: 'PP No. 71 Tahun 2019',
        year: 2019,
        title: 'PSTE',
        pasalTurunan: 'Pasal 5 ayat (2)',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Perlu Sinkronisasi Pengecualian',
        ringkasanDampak: 'Kewajiban filtering PSE wajib mengecualikan transmisi konten privat antar dua individu.',
        uuIndukSebelum: 'Larangan kesusilaan tanpa kualifikasi "untuk diketahui umum".',
        uuIndukSesudah: 'Wajib memenuhi unsur publisitas "untuk diketahui umum".',
        ketentuanTurunanTerdampak: 'Tata kelola takedown konten asusila oleh PSE.',
        penjelasanPertentangan: 'PSE dilarang memblokir komunikasi privat terenkripsi end-to-end tanpa adanya distribusi ke ruang publik.',
        rekomendasiHarmonisasi: 'Harmonisasi Permen Komdigi terkait batasan intervensi ruang percakapan privat.',
      },
    ],
  },

  // ── Pasal 27 ayat (3) ─────────────────────────────────────────────────────
  'uu-11-2008/pasal-27/ayat-3': {
    canonicalPath: 'uu-11-2008/pasal-27/ayat-3',
    pasalLabel: 'Pasal 27 ayat (3)',
    diubahOleh: 'UU No. 1 Tahun 2024 (Dihapus) jo. UU No. 19 Tahun 2016',
    tanggalPengundangan: 'Disahkan: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'DICABUT',
    statusBadge: '🔴 Ketentuan Norma Dihapus / Dicabut',
    textSebelum: 'Setiap Orang dengan sengaja dan tanpa hak mendistribusikan dan/atau mentransmisikan dan/atau membuat dapat diaksesnya Informasi Elektronik dan/atau Dokumen Elektronik yang memiliki muatan penghinaan dan/atau pencemaran nama baik.',
    textSesudah: '[KETENTUAN AYAT DIHAPUS OLEH PASAL I ANGKA 2 HURUF b UU NO. 1 TAHUN 2024]. Norma delik dialihkan dan diperinci secara ketat ke dalam Pasal 27A.',
    putusanMk: {
      nomor: 'Putusan MK No. 50/PUU-VI/2008 & Putusan No. 2/PUU-VII/2009',
      tahun: 2008,
      amarPutusan: 'Ketentuan ini merupakan delik aduan dan merujuk pada Pasal 310 dan 311 KUHP.',
      ratioDecidendi: 'Menjamin agar penegak hukum tidak menggunakan delik ini secara ex-officio tanpa adanya permohonan dari korban yang merasa dicemarkan nama baiknya.',
    },
    latarBelakangPerubahan: 'Pembentuk Undang-Undang mencabut Pasal 27 ayat (3) secara eksplisit melalui Pasal I angka 2 UU No. 1 Tahun 2024 karena pasal ini paling sering disalahgunakan untuk mengkriminalisasi warga. Rumusan delik dipindahkan dan diperinci dalam Pasal 27A.',
    peraturanTerdampak: [
      {
        id: 'pp-71-2019-pasal-5-p27a3',
        type: 'PP',
        number: 'PP No. 71 Tahun 2019',
        year: 2019,
        title: 'Penyelenggaraan Sistem dan Transaksi Elektronik',
        pasalTurunan: 'Pasal 5 & Pasal 21',
        status: 'HILANG_CANTOLAN',
        statusLabel: '⚠️ Kehilangan Cantolan Yuridis',
        ringkasanDampak: 'Kewenangan takedown konten pencemaran nama baik pada PP 71/2019 kehilangan rujukan norma induk UU.',
        uuIndukSebelum: 'Pasal 27 ayat (3) memuat norma larangan penghinaan dan pencemaran nama baik di ruang siber.',
        uuIndukSesudah: 'Pasal 27 ayat (3) DICABUT 100% oleh Pasal I angka 2 UU 1/2024.',
        ketentuanTurunanTerdampak: 'Pasal 5 ayat (2) PP 71/2019 mengenai konten yang dilarang.',
        penjelasanPertentangan: 'PP tidak boleh mengatur sanksi atau pelarangan yang norma induknya dalam undang-undang telah dihapus.',
        rekomendasiHarmonisasi: 'Segera lakukan revisi PP 71/2019 untuk mencabut klausul terkait Pasal 27 ayat (3).',
      },
      {
        id: 'skb-pedoman-polri-2021',
        type: 'SKB',
        number: 'Surat Telegram Kapolri No. ST/339/II/RES.1.1.1./2021',
        year: 2021,
        title: 'Pedoman Penanganan Perkara Siber Pasal 27 ayat (3)',
        pasalTurunan: 'Petunjuk Teknis Gelar Perkara Siber',
        status: 'USANG',
        statusLabel: '🔴 Tidak Berlaku Lagi',
        ringkasanDampak: 'Surat Telegram Kapolri terkait Pasal 27 ayat (3) tidak dapat dijadikan rujukan penyidikan lagi.',
        uuIndukSebelum: 'Pasal 27 ayat (3) rujukan laporan pidana penghinaan.',
        uuIndukSesudah: 'Laporan wajib merujuk Pasal 27A dengan syarat pembuktian tuduhan perbuatan spesifik.',
        ketentuanTurunanTerdampak: 'Format Laporan Polisi (LP) di Bareskrim dan Polda.',
        penjelasanPertentangan: 'Penyidik yang menerbitkan LP dengan sangkaan Pasal 27 ayat (3) pasca 2 Januari 2024 batal demi hukum.',
        rekomendasiHarmonisasi: 'Kapolri menerbitkan Telegram Rahasia pembaruan format sangkaan pidana ke Pasal 27A.',
      },
    ],
  },

  // ── Pasal 27 ayat (4) ─────────────────────────────────────────────────────
  'uu-11-2008/pasal-27/ayat-4': {
    canonicalPath: 'uu-11-2008/pasal-27/ayat-4',
    pasalLabel: 'Pasal 27 ayat (4)',
    diubahOleh: 'UU No. 1 Tahun 2024 (Dihapus) jo. UU No. 19 Tahun 2016',
    tanggalPengundangan: 'Disahkan: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'LN RI Tahun 2024 No. 8, TLN No. 6916',
    statusPerubahan: 'DICABUT',
    statusBadge: '🔴 Ketentuan Norma Dihapus / Dicabut',
    textSebelum: 'Setiap Orang dengan sengaja dan tanpa hak mendistribusikan dan/atau mentransmisikan dan/atau membuat dapat diaksesnya Informasi Elektronik dan/atau Dokumen Elektronik yang memiliki muatan pemerasan dan/atau pengancaman.',
    textSesudah: '[KETENTUAN AYAT DIHAPUS OLEH PASAL I ANGKA 2 HURUF c UU NO. 1 TAHUN 2024]. Norma pemerasan dan pengancaman dialihkan ke Pasal 27B.',
    latarBelakangPerubahan: 'Ketentuan dihapus dan diperluas konstruksinya ke Pasal 27B yang memisahkan secara spesifik antara ancaman pencemaran dengan ancaman kekerasan fisik.',
    peraturanTerdampak: [
      {
        id: 'skb-pemerasan-2021',
        type: 'SKB',
        number: 'SKB 3 Menteri Pedoman UU ITE',
        year: 2021,
        title: 'Pedoman Pasal 27 ayat (4)',
        pasalTurunan: 'Angka 4 Lampiran SKB',
        status: 'USANG',
        statusLabel: '🔴 Tidak Berlaku Lagi',
        ringkasanDampak: 'Pedoman kehilangan objek pengaturan karena pasal telah dipindahkan ke Pasal 27B.',
        uuIndukSebelum: 'Pasal 27 ayat (4) UU ITE 2016.',
        uuIndukSesudah: 'Pasal 27B UU 1/2024.',
        ketentuanTurunanTerdampak: 'Pedoman penuntutan jaksa.',
        penjelasanPertentangan: 'Rujukan pasal dalam surat dakwaan harus diperbarui ke Pasal 27B.',
        rekomendasiHarmonisasi: 'Kejaksaan menerbitkan SE pedoman dakwaan Pasal 27B.',
      },
    ],
  },

  // ── Pasal 27A (Sisipan Baru UU 1/2024) ────────────────────────────────────
  'uu-11-2008/pasal-27a': {
    canonicalPath: 'uu-11-2008/pasal-27a',
    pasalLabel: 'Pasal 27A',
    diubahOleh: 'UU No. 1 Tahun 2024 tentang Perubahan Kedua UU ITE (Pasal I angka 3)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'Lembaran Negara Republik Indonesia Tahun 2024 Nomor 8, Tambahan Lembaran Negara Nomor 6916',
    statusPerubahan: 'SISIPAN_BARU',
    statusBadge: '🟢 Sisipan Baru (Hukum Positif Berlaku)',
    textSebelum: '(Ketentuan norma belum ada pada UU No. 11 Tahun 2008 maupun UU No. 19 Tahun 2016)',
    textSesudah: 'Setiap Orang dengan sengaja menyerang kehormatan atau nama baik orang lain dengan cara menuduhkan suatu hal, dengan maksud supaya hal tersebut diketahui umum dalam bentuk Informasi Elektronik dan/atau Dokumen Elektronik yang dilakukan melalui Sistem Elektronik.',
    putusanMk: {
      nomor: 'Putusan MK No. 50/PUU-VI/2008 (Pondasi Konstitusional)',
      tahun: 2008,
      amarPutusan: 'Konstruksi delik kehormatan wajib selaras dengan delik aduan KUHP.',
      ratioDecidendi: 'Membedakan secara tegas antara penghinaan biasa, penistaan, dan penyerangan kehormatan demi kepentingan umum.',
    },
    latarBelakangPerubahan: 'Disisipkan untuk menggantikan Pasal 27 ayat (3) lama dengan rumusan yang jauh lebih ketat: menuntut adanya tuduhan perbuatan spesifik (bukan sekadar kata-kata makian), mewajibkan maksud agar diketahui umum, serta mengecualikan kritik demi kepentingan umum atau pembelaan diri.',
    peraturanTerdampak: [
      {
        id: 'pp-71-2019-pasal-27a',
        type: 'PP',
        number: 'PP No. 71 Tahun 2019',
        year: 2019,
        title: 'PSTE (Penyelenggaraan Sistem dan Transaksi Elektronik)',
        pasalTurunan: 'Pasal 21 ayat (1)',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Perlu Sinkronisasi Standar Moderasi',
        ringkasanDampak: 'SOP takedown konten PSE harus memverifikasi bukti aduan korban sebelum melakukan penutupan akun/takedown.',
        uuIndukSebelum: 'Belum ada Pasal 27A (pada naskah UU ITE 2008/2016).',
        uuIndukSesudah: 'Pasal 27A UU 1/2024: Penyerangan kehormatan merupakan delik aduan absolut dengan klausul pembenar kepentingan umum.',
        ketentuanTurunanTerdampak: 'Kewajiban PSE melakukan penyaringan mandiri (filtering) konten terlarang.',
        penjelasanPertentangan: 'PSE dilarang secara sepihak memutus akses kritik publik terhadap pejabat karena Pasal 27A mengecualikan perbuatan demi kepentingan umum.',
        rekomendasiHarmonisasi: 'Kementerian Komdigi menerbitkan Peraturan Menteri petunjuk teknis verifikasi aduan Pasal 27A bagi platform PSE.',
      },
      {
        id: 'sema-kejaksaan-2024',
        type: 'PERMEN',
        number: 'Pedoman Penuntutan Kejaksaan Agung RI No. 1/2024',
        year: 2024,
        title: 'Pedoman Penanganan Perkara Tindak Pidana Siber',
        pasalTurunan: 'BAB IV Prosedur Pembuktian Delik Aduan',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Harmonisasi Acara Penuntutan',
        ringkasanDampak: 'Penuntut umum wajib memastikan berkas perkara memuat surat pengaduan asli dari korban langsung (bukan kuasa hukum/pihak ketiga).',
        uuIndukSebelum: 'Pasal 27 ayat (3) lama sering diterima tanpa pemeriksaan ketat legal standing pelapor.',
        uuIndukSesudah: 'Pasal 45 ayat (4) jo. Pasal 27A UU 1/2024 menegaskan hanya korban langsung yang memiliki hak mengadu.',
        ketentuanTurunanTerdampak: 'Instruksi Jaksa Agung mengenai syarat formil penuntutan siber.',
        penjelasanPertentangan: 'Bila jaksa menerima berkas tanpa aduan korban langsung, surat dakwaan batal demi hukum.',
        rekomendasiHarmonisasi: 'Kejaksaan menerbitkan surat edaran kepada seluruh Kejati & Kejari se-Indonesia untuk menolak berkas tanpa aduan prinsipal.',
      },
    ],
  },

  // ── Pasal 27B (Sisipan Baru UU 1/2024) ────────────────────────────────────
  'uu-11-2008/pasal-27b': {
    canonicalPath: 'uu-11-2008/pasal-27b',
    pasalLabel: 'Pasal 27B',
    diubahOleh: 'UU No. 1 Tahun 2024 tentang Perubahan Kedua UU ITE (Pasal I angka 3)',
    tanggalPengundangan: 'Disahkan di Jakarta: 2 Januari 2024 | Diundangkan: 2 Januari 2024',
    disahkanOleh: 'Presiden RI Joko Widodo & Diundangkan oleh Mensesneg Pratikno',
    lembaranNegara: 'Lembaran Negara Republik Indonesia Tahun 2024 Nomor 8, Tambahan Lembaran Negara Nomor 6916',
    statusPerubahan: 'SISIPAN_BARU',
    statusBadge: '🟢 Sisipan Baru (Hukum Positif Berlaku)',
    textSebelum: '(Ketentuan norma belum ada pada UU No. 11 Tahun 2008 maupun UU No. 19 Tahun 2016)',
    textSesudah: '(1) Setiap Orang dengan sengaja dan tanpa hak mendistribusikan... dengan maksud untuk menguntungkan diri sendiri... memaksa orang dengan ancaman pencemaran.\n(2) Setiap Orang dengan sengaja dan tanpa hak mendistribusikan... yang berisi ancaman membuka rahasia.',
    latarBelakangPerubahan: 'Disisipkan khusus untuk menjerat delik pemerasan digital dan ancaman pencemaran (doxing untuk memeras), memisahkan antara ancaman fisik dengan ancaman membuka rahasia/aib di media sosial.',
    peraturanTerdampak: [
      {
        id: 'permen-kominfo-fintech-2024',
        type: 'PERMEN',
        number: 'Permenkominfo / Regulasi OJK Pelindungan Konsumen',
        year: 2024,
        title: 'Perlindungan Konsumen Terhadap Praktik Penagihan Pinjaman Online',
        pasalTurunan: 'Ketentuan Larangan Teror & Ancaman Penagihan Digital',
        status: 'PERLU_PENYESUAIAN',
        statusLabel: '⚠️ Harmonisasi Penegakan Hukum Pinjol',
        ringkasanDampak: 'Praktik penagihan pinjol ilegal yang mengancam menyebarkan foto atau data debitur kini langsung terikat delik Pasal 27B UU 1/2024.',
        uuIndukSebelum: 'Diatur terpisah dalam delik umum pemerasan KUHP dan Pasal 27 ayat (4) UU ITE lama.',
        uuIndukSesudah: 'Pasal 27B UU 1/2024: Memuat ancaman pidana hingga 6 tahun bagi siapa pun yang mengancam membuka rahasia untuk memeras.',
        ketentuanTurunanTerdampak: 'Regulasi penagihan etis pinjol di OJK dan Kominfo.',
        penjelasanPertentangan: 'Aturan administratif sebelumnya hanya memuat sanksi pencabutan izin, kini wajib disinkronkan dengan laporan pidana Pasal 27B.',
        rekomendasiHarmonisasi: 'OJK dan Komdigi menyusun nota kesepahaman penanganan cepat pemblokiran rekening & aplikasi pinjol yang melanggar Pasal 27B.',
      },
    ],
  }
};
